#!/bin/bash

#SBATCH --chdir /home/semansou/slurm/
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 20G
#SBATCH --gres gpu
#SBATCH --time 04:00:00
#SBATCH -o out/%j.out
#SBATCH -e err/%j.err

echo STARTING AT $(date)
echo "hello from $(hostname)"

module load gcc/8.4.0-cuda
module load python/3.7.7
module load mvapich2/2.3.4
#module load opencv/4.2.0-cuda-openmp
module load py-tensorflow/2.3.1-cuda-mpi
#module load cuda/11.0.2
module load py-keras/2.2.4
module load py-scikit-learn/0.23.1-openmp
#module load py-torch/1.6.0-cuda-openmp
#module load py-torchvision/0.6.1
module load py-h5py
module load py-mpi4py


#virtualenv --system-site-packages venvs/tf
#pip install --no-cache-dir --user pyyaml
#pip install --no-cache-dir --user keras_applications
#pip install --no-cache-dir --user joblib
#pip install --no-cache-dir --user tqdm
#pip install --no-cache-dir --user tensorboard
#pip install --no-cache-dir --user tensorflow-addons
#pip install --no-cache-dir --user notebook

cd

source venvs/tf/bin/activate

export WANDB_API_KEY=79ee9f3298738a1d4250527b14bfa67d64ff40b7
export WANDB_MODE=offline
wandb login

python ./code/long_range_prediction/evaluate_batch.py --config=${CONFIG}
#python attention/main.py train-markov-chain --config=${CONFIG} --seed=1234 --outpath=${PATH_NAME}

deactivate
module purge

echo "by from $(hostname)"
echo FINISHED AT $(date)
